ERROR - 2023-05-03 10:41:18 --> Error connecting to the database: mysqli_sql_exception: Connection refused in /var/www/html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('127.0.0.1', 'root', 'admin', 'taskapp', 3306, '', 0)
#1 /var/www/html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /var/www/html/system/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/html/system/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 /var/www/html/app/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
#7 /var/www/html/system/CodeIgniter.php(927): App\Controllers\Tasks->index()
#8 /var/www/html/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
#9 /var/www/html/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /var/www/html/public/index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Connection refused in /var/www/html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /var/www/html/system/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 /var/www/html/system/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#5 /var/www/html/app/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
#6 /var/www/html/system/CodeIgniter.php(927): App\Controllers\Tasks->index()
#7 /var/www/html/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
#8 /var/www/html/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /var/www/html/public/index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-05-03 10:41:18 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `task`', [], false)
 3 SYSTEMPATH/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH/CodeIgniter.php(927): App\Controllers\Tasks->index()
 7 SYSTEMPATH/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
 8 SYSTEMPATH/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-03 10:41:24 --> Error connecting to the database: mysqli_sql_exception: Connection refused in /var/www/html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('127.0.0.1', 'root', 'admin', 'taskapp', 3306, '', 0)
#1 /var/www/html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /var/www/html/system/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/html/system/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 /var/www/html/app/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
#7 /var/www/html/system/CodeIgniter.php(927): App\Controllers\Tasks->index()
#8 /var/www/html/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
#9 /var/www/html/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /var/www/html/public/index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Connection refused in /var/www/html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /var/www/html/system/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 /var/www/html/system/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#5 /var/www/html/app/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
#6 /var/www/html/system/CodeIgniter.php(927): App\Controllers\Tasks->index()
#7 /var/www/html/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
#8 /var/www/html/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /var/www/html/public/index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-05-03 10:41:24 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `task`', [], false)
 3 SYSTEMPATH/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH/CodeIgniter.php(927): App\Controllers\Tasks->index()
 7 SYSTEMPATH/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
 8 SYSTEMPATH/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-03 10:41:28 --> Error connecting to the database: mysqli_sql_exception: Connection refused in /var/www/html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('127.0.0.1', 'root', 'admin', 'taskapp', 3306, '', 0)
#1 /var/www/html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /var/www/html/system/Model.php(182): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/html/system/BaseModel.php(524): CodeIgniter\Model->doFind(true, '1')
#6 /var/www/html/app/Controllers/Tasks.php(115): CodeIgniter\BaseModel->find('1')
#7 /var/www/html/app/Controllers/Tasks.php(25): App\Controllers\Tasks->getTaskOr404('1')
#8 /var/www/html/system/CodeIgniter.php(927): App\Controllers\Tasks->show('1')
#9 /var/www/html/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
#10 /var/www/html/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/html/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Connection refused in /var/www/html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /var/www/html/system/Model.php(182): CodeIgniter\Database\BaseBuilder->get()
#4 /var/www/html/system/BaseModel.php(524): CodeIgniter\Model->doFind(true, '1')
#5 /var/www/html/app/Controllers/Tasks.php(115): CodeIgniter\BaseModel->find('1')
#6 /var/www/html/app/Controllers/Tasks.php(25): App\Controllers\Tasks->getTaskOr404('1')
#7 /var/www/html/system/CodeIgniter.php(927): App\Controllers\Tasks->show('1')
#8 /var/www/html/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
#9 /var/www/html/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /var/www/html/public/index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-05-03 10:41:28 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `task`
WHERE `task`.`id` = :task.id:', [...], false)
 3 SYSTEMPATH/Model.php(182): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(524): CodeIgniter\Model->doFind(true, '1')
 5 APPPATH/Controllers/Tasks.php(115): CodeIgniter\BaseModel->find('1')
 6 APPPATH/Controllers/Tasks.php(25): App\Controllers\Tasks->getTaskOr404('1')
 7 SYSTEMPATH/CodeIgniter.php(927): App\Controllers\Tasks->show('1')
 8 SYSTEMPATH/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
 9 SYSTEMPATH/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-03 10:42:35 --> Error connecting to the database: mysqli_sql_exception: Connection refused in /var/www/html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('127.0.0.1', 'root', 'admin', 'taskapp', 3306, '', 0)
#1 /var/www/html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /var/www/html/system/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/html/system/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 /var/www/html/app/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
#7 /var/www/html/system/CodeIgniter.php(927): App\Controllers\Tasks->index()
#8 /var/www/html/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
#9 /var/www/html/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /var/www/html/public/index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Connection refused in /var/www/html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /var/www/html/system/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 /var/www/html/system/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#5 /var/www/html/app/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
#6 /var/www/html/system/CodeIgniter.php(927): App\Controllers\Tasks->index()
#7 /var/www/html/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
#8 /var/www/html/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /var/www/html/public/index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-05-03 10:42:35 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `task`', [], false)
 3 SYSTEMPATH/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH/CodeIgniter.php(927): App\Controllers\Tasks->index()
 7 SYSTEMPATH/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
 8 SYSTEMPATH/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-03 10:44:30 --> Error connecting to the database: mysqli_sql_exception: Connection refused in /var/www/html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('127.0.0.1', 'root', 'admin', 'taskapp', 3306, '', 0)
#1 /var/www/html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /var/www/html/system/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/html/system/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 /var/www/html/app/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
#7 /var/www/html/system/CodeIgniter.php(927): App\Controllers\Tasks->index()
#8 /var/www/html/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
#9 /var/www/html/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /var/www/html/public/index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Connection refused in /var/www/html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /var/www/html/system/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 /var/www/html/system/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#5 /var/www/html/app/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
#6 /var/www/html/system/CodeIgniter.php(927): App\Controllers\Tasks->index()
#7 /var/www/html/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
#8 /var/www/html/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /var/www/html/public/index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-05-03 10:44:30 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `task`', [], false)
 3 SYSTEMPATH/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH/CodeIgniter.php(927): App\Controllers\Tasks->index()
 7 SYSTEMPATH/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
 8 SYSTEMPATH/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-03 10:48:24 --> Error connecting to the database: mysqli_sql_exception: No such file or directory in /var/www/html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('localhost', 'root', 'admin', 'taskapp', 3306, '', 0)
#1 /var/www/html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /var/www/html/system/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/html/system/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 /var/www/html/app/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
#7 /var/www/html/system/CodeIgniter.php(927): App\Controllers\Tasks->index()
#8 /var/www/html/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
#9 /var/www/html/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /var/www/html/public/index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No such file or directory in /var/www/html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /var/www/html/system/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 /var/www/html/system/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#5 /var/www/html/app/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
#6 /var/www/html/system/CodeIgniter.php(927): App\Controllers\Tasks->index()
#7 /var/www/html/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
#8 /var/www/html/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /var/www/html/public/index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-05-03 10:48:24 --> Unable to connect to the database.
Main connection [MySQLi]: No such file or directory
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `task`', [], false)
 3 SYSTEMPATH/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH/CodeIgniter.php(927): App\Controllers\Tasks->index()
 7 SYSTEMPATH/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
 8 SYSTEMPATH/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-03 10:49:13 --> Error connecting to the database: mysqli_sql_exception: Connection timed out in /var/www/html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('192.0.0.1', 'root', 'admin', 'taskapp', 3306, '', 0)
#1 /var/www/html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /var/www/html/system/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/html/system/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 /var/www/html/app/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
#7 /var/www/html/system/CodeIgniter.php(927): App\Controllers\Tasks->index()
#8 /var/www/html/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
#9 /var/www/html/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /var/www/html/public/index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Connection timed out in /var/www/html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /var/www/html/system/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 /var/www/html/system/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#5 /var/www/html/app/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
#6 /var/www/html/system/CodeIgniter.php(927): App\Controllers\Tasks->index()
#7 /var/www/html/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
#8 /var/www/html/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /var/www/html/public/index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-05-03 10:49:14 --> Unable to connect to the database.
Main connection [MySQLi]: Connection timed out
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `task`', [], false)
 3 SYSTEMPATH/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH/CodeIgniter.php(927): App\Controllers\Tasks->index()
 7 SYSTEMPATH/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
 8 SYSTEMPATH/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-03 10:49:29 --> Error connecting to the database: mysqli_sql_exception: Connection timed out in /var/www/html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('192.0.0.1', 'root', 'admin', 'taskapp', 3306, '', 0)
#1 /var/www/html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /var/www/html/system/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/html/system/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 /var/www/html/app/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
#7 /var/www/html/system/CodeIgniter.php(927): App\Controllers\Tasks->index()
#8 /var/www/html/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
#9 /var/www/html/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /var/www/html/public/index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Connection timed out in /var/www/html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /var/www/html/system/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 /var/www/html/system/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#5 /var/www/html/app/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
#6 /var/www/html/system/CodeIgniter.php(927): App\Controllers\Tasks->index()
#7 /var/www/html/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
#8 /var/www/html/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /var/www/html/public/index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-05-03 10:49:29 --> Unable to connect to the database.
Main connection [MySQLi]: Connection timed out
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `task`', [], false)
 3 SYSTEMPATH/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH/CodeIgniter.php(927): App\Controllers\Tasks->index()
 7 SYSTEMPATH/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
 8 SYSTEMPATH/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-03 10:50:26 --> Error connecting to the database: mysqli_sql_exception: Connection refused in /var/www/html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('127.0.0.1', 'root', 'admin', 'taskapp', 3306, '', 0)
#1 /var/www/html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /var/www/html/system/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/html/system/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 /var/www/html/app/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
#7 /var/www/html/system/CodeIgniter.php(927): App\Controllers\Tasks->index()
#8 /var/www/html/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
#9 /var/www/html/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /var/www/html/public/index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Connection refused in /var/www/html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /var/www/html/system/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 /var/www/html/system/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#5 /var/www/html/app/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
#6 /var/www/html/system/CodeIgniter.php(927): App\Controllers\Tasks->index()
#7 /var/www/html/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
#8 /var/www/html/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /var/www/html/public/index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-05-03 10:50:26 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `task`', [], false)
 3 SYSTEMPATH/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH/CodeIgniter.php(927): App\Controllers\Tasks->index()
 7 SYSTEMPATH/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
 8 SYSTEMPATH/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-03 10:51:41 --> Error connecting to the database: mysqli_sql_exception: Connection refused in /var/www/html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('109.0.0.0', 'root', 'admin', 'taskapp', 3306, '', 0)
#1 /var/www/html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /var/www/html/system/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/html/system/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 /var/www/html/app/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
#7 /var/www/html/system/CodeIgniter.php(927): App\Controllers\Tasks->index()
#8 /var/www/html/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
#9 /var/www/html/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /var/www/html/public/index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Connection refused in /var/www/html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /var/www/html/system/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 /var/www/html/system/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#5 /var/www/html/app/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
#6 /var/www/html/system/CodeIgniter.php(927): App\Controllers\Tasks->index()
#7 /var/www/html/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
#8 /var/www/html/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /var/www/html/public/index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-05-03 10:51:41 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `task`', [], false)
 3 SYSTEMPATH/Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH/Controllers/Tasks.php(18): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH/CodeIgniter.php(927): App\Controllers\Tasks->index()
 7 SYSTEMPATH/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Tasks))
 8 SYSTEMPATH/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-03 11:01:23 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in /var/www/html/system/Database/MySQLi/Connection.php:292
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 /var/www/html/system/Database/BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 /var/www/html/system/Database/BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 /var/www/html/system/Database/BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /var/www/html/system/Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 /var/www/html/system/BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 /var/www/html/system/Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 /var/www/html/app/Controllers/Signup.php(18): CodeIgniter\Model->insert(Object(App\Entities\User))
#8 /var/www/html/system/CodeIgniter.php(927): App\Controllers\Signup->create()
#9 /var/www/html/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
#10 /var/www/html/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/html/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-05-03 11:01:23 --> Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 292.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(292): mysqli->query('INSERT INTO `user` (`name`, `email`, `created_at`, `updated_at`) VALUES (\'Dave\', \'dave@example.com\', \'2023-05-03 11:01:23\', \'2023-05-03 11:01:23\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`name`, `email`, `created_at`, `updated_at`) VALUES (\'Dave\', \'dave@example.com\', \'2023-05-03 11:01:23\', \'2023-05-03 11:01:23\')')
 3 SYSTEMPATH/Database/BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`name`, `email`, `created_at`, `updated_at`) VALUES (\'Dave\', \'dave@example.com\', \'2023-05-03 11:01:23\', \'2023-05-03 11:01:23\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `email`, `created_at`, `updated_at`) VALUES (:name:, :email:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH/Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH/Controllers/Signup.php(18): CodeIgniter\Model->insert(Object(App\Entities\User))
 9 SYSTEMPATH/CodeIgniter.php(927): App\Controllers\Signup->create()
10 SYSTEMPATH/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
11 SYSTEMPATH/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-03 11:05:21 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in /var/www/html/system/Database/MySQLi/Connection.php:292
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 /var/www/html/system/Database/BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 /var/www/html/system/Database/BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 /var/www/html/system/Database/BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /var/www/html/system/Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 /var/www/html/system/BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 /var/www/html/system/Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 /var/www/html/app/Controllers/Signup.php(18): CodeIgniter\Model->insert(Object(App\Entities\User))
#8 /var/www/html/system/CodeIgniter.php(927): App\Controllers\Signup->create()
#9 /var/www/html/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
#10 /var/www/html/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/html/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-05-03 11:05:21 --> Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 292.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(292): mysqli->query('INSERT INTO `user` (`name`, `email`, `created_at`, `updated_at`) VALUES (\'Dave\', \'dave@example.com\', \'2023-05-03 11:05:21\', \'2023-05-03 11:05:21\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`name`, `email`, `created_at`, `updated_at`) VALUES (\'Dave\', \'dave@example.com\', \'2023-05-03 11:05:21\', \'2023-05-03 11:05:21\')')
 3 SYSTEMPATH/Database/BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`name`, `email`, `created_at`, `updated_at`) VALUES (\'Dave\', \'dave@example.com\', \'2023-05-03 11:05:21\', \'2023-05-03 11:05:21\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `email`, `created_at`, `updated_at`) VALUES (:name:, :email:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH/Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH/Controllers/Signup.php(18): CodeIgniter\Model->insert(Object(App\Entities\User))
 9 SYSTEMPATH/CodeIgniter.php(927): App\Controllers\Signup->create()
10 SYSTEMPATH/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
11 SYSTEMPATH/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-03 11:05:54 --> Error connecting to the database: mysqli_sql_exception: Operation timed out in /Users/tiffany/Desktop/dev/ia-tiffany/www/system/Database/MySQLi/Connection.php:170
Stack trace:
#0 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/Database/MySQLi/Connection.php(170): mysqli->real_connect('172.19.0.1', 'root', Object(SensitiveParameterValue), 'taskapp', 3306, '', 0)
#1 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/Database/BaseConnection.php(1360): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#4 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/Database/BaseConnection.php(1394): CodeIgniter\Database\BaseConnection->listTables()
#5 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/Database/MigrationRunner.php(759): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#6 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/Database/MigrationRunner.php(167): CodeIgniter\Database\MigrationRunner->ensureTable()
#7 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/Commands/Database/Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/CLI/Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/CLI/CommandRunner.php(65): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/CLI/CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index(Array)
#11 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/CodeIgniter.php(920): CodeIgniter\CLI\CommandRunner->_remap('index', Array)
#12 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/CodeIgniter.php(347): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/CLI/Console.php(48): CodeIgniter\CodeIgniter->run()
#15 /Users/tiffany/Desktop/dev/ia-tiffany/www/spark(98): CodeIgniter\CLI\Console->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Operation timed out in /Users/tiffany/Desktop/dev/ia-tiffany/www/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/Database/BaseConnection.php(1360): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#3 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/Database/BaseConnection.php(1394): CodeIgniter\Database\BaseConnection->listTables()
#4 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/Database/MigrationRunner.php(759): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#5 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/Database/MigrationRunner.php(167): CodeIgniter\Database\MigrationRunner->ensureTable()
#6 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/Commands/Database/Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#7 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/CLI/Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#8 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/CLI/CommandRunner.php(65): CodeIgniter\CLI\Commands->run('migrate', Array)
#9 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/CLI/CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index(Array)
#10 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/CodeIgniter.php(920): CodeIgniter\CLI\CommandRunner->_remap('index', Array)
#11 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#12 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/CodeIgniter.php(347): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /Users/tiffany/Desktop/dev/ia-tiffany/www/system/CLI/Console.php(48): CodeIgniter\CodeIgniter->run()
#14 /Users/tiffany/Desktop/dev/ia-tiffany/www/spark(98): CodeIgniter\CLI\Console->run()
#15 {main}
CRITICAL - 2023-05-03 11:06:58 --> syntax error, unexpected identifier "username", expecting "]"
in APPPATH/Config/Database.php on line 36.
 1 SYSTEMPATH/Autoloader/Autoloader.php(259): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH/Config/Database.php')
 2 SYSTEMPATH/Autoloader/Autoloader.php(237): CodeIgniter\Autoloader\Autoloader->loadInNamespace('Config\\Database')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('Config\\Database')
 4 SYSTEMPATH/Config/Factories.php(155): class_exists('Config\\Database')
 5 SYSTEMPATH/Config/Factories.php(125): CodeIgniter\Config\Factories::locateClass([...], 'Database')
 6 SYSTEMPATH/Common.php(203): CodeIgniter\Config\Factories::__callStatic('config', [])
 7 SYSTEMPATH/Database/MigrationRunner.php(144): config('Database')
 8 SYSTEMPATH/Config/Services.php(407): CodeIgniter\Database\MigrationRunner->__construct(Object(Config\Migrations), null)
 9 SYSTEMPATH/Config/BaseService.php(253): CodeIgniter\Config\Services::migrations(Object(Config\Migrations), null, false)
10 SYSTEMPATH/Config/BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('migrations', [...])
11 SYSTEMPATH/Config/Services.php(402): CodeIgniter\Config\BaseService::getSharedInstance('migrations', null, null)
12 SYSTEMPATH/Config/BaseService.php(253): CodeIgniter\Config\Services::migrations()
13 SYSTEMPATH/Commands/Database/Migrate.php(69): CodeIgniter\Config\BaseService::__callStatic('migrations', [])
14 SYSTEMPATH/CLI/Commands.php(63): CodeIgniter\Commands\Database\Migrate->run([])
15 SYSTEMPATH/CLI/CommandRunner.php(65): CodeIgniter\CLI\Commands->run('migrate', [])
16 SYSTEMPATH/CLI/CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index([])
17 SYSTEMPATH/CodeIgniter.php(920): CodeIgniter\CLI\CommandRunner->_remap('index', [...])
18 SYSTEMPATH/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
19 SYSTEMPATH/CodeIgniter.php(347): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
20 SYSTEMPATH/CLI/Console.php(48): CodeIgniter\CodeIgniter->run()
21 ROOTPATH/spark(98): CodeIgniter\CLI\Console->run()
CRITICAL - 2023-05-03 11:08:39 --> syntax error, unexpected identifier "username", expecting "]"
in APPPATH/Config/Database.php on line 36.
 1 SYSTEMPATH/Autoloader/Autoloader.php(259): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH/Config/Database.php')
 2 SYSTEMPATH/Autoloader/Autoloader.php(237): CodeIgniter\Autoloader\Autoloader->loadInNamespace('Config\\Database')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('Config\\Database')
 4 SYSTEMPATH/Config/Factories.php(155): class_exists('Config\\Database')
 5 SYSTEMPATH/Config/Factories.php(125): CodeIgniter\Config\Factories::locateClass([...], 'Database')
 6 SYSTEMPATH/Common.php(203): CodeIgniter\Config\Factories::__callStatic('config', [])
 7 SYSTEMPATH/Database/MigrationRunner.php(144): config('Database')
 8 SYSTEMPATH/Config/Services.php(407): CodeIgniter\Database\MigrationRunner->__construct(Object(Config\Migrations), null)
 9 SYSTEMPATH/Config/BaseService.php(253): CodeIgniter\Config\Services::migrations(Object(Config\Migrations), null, false)
10 SYSTEMPATH/Config/BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('migrations', [...])
11 SYSTEMPATH/Config/Services.php(402): CodeIgniter\Config\BaseService::getSharedInstance('migrations', null, null)
12 SYSTEMPATH/Config/BaseService.php(253): CodeIgniter\Config\Services::migrations()
13 SYSTEMPATH/Commands/Database/MigrateRollback.php(81): CodeIgniter\Config\BaseService::__callStatic('migrations', [])
14 SYSTEMPATH/CLI/Commands.php(63): CodeIgniter\Commands\Database\MigrateRollback->run([...])
15 SYSTEMPATH/CLI/CommandRunner.php(65): CodeIgniter\CLI\Commands->run('migrate:rollback', [...])
16 SYSTEMPATH/CLI/CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index([...])
17 SYSTEMPATH/CodeIgniter.php(920): CodeIgniter\CLI\CommandRunner->_remap('index', [...])
18 SYSTEMPATH/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
19 SYSTEMPATH/CodeIgniter.php(347): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
20 SYSTEMPATH/CLI/Console.php(48): CodeIgniter\CodeIgniter->run()
21 ROOTPATH/spark(98): CodeIgniter\CLI\Console->run()
