ERROR - 2023-09-21 10:10:46 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'taskapp' in /var/www/html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('172.19.0.1', 'root', 'admin', 'taskapp', 3306, '', 0)
#1 /var/www/html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /var/www/html/system/Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/html/system/BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 /var/www/html/app/Models/UserModel.php(73): CodeIgniter\BaseModel->first()
#7 /var/www/html/app/Libraries/Authentication.php(13): App\Models\UserModel->findByEmail('admin@example.c...')
#8 /var/www/html/app/Controllers/Login.php(21): App\Libraries\Authentication->login('admin@example.c...', 'secret', false)
#9 /var/www/html/system/CodeIgniter.php(927): App\Controllers\Login->create()
#10 /var/www/html/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#11 /var/www/html/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /var/www/html/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'taskapp' in /var/www/html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /var/www/html/system/Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 /var/www/html/system/BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 /var/www/html/app/Models/UserModel.php(73): CodeIgniter\BaseModel->first()
#6 /var/www/html/app/Libraries/Authentication.php(13): App\Models\UserModel->findByEmail('admin@example.c...')
#7 /var/www/html/app/Controllers/Login.php(21): App\Libraries\Authentication->login('admin@example.c...', 'secret', false)
#8 /var/www/html/system/CodeIgniter.php(927): App\Controllers\Login->create()
#9 /var/www/html/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 /var/www/html/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/html/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-09-21 10:10:46 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'taskapp'
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH/Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH/Models/UserModel.php(73): CodeIgniter\BaseModel->first()
 6 APPPATH/Libraries/Authentication.php(13): App\Models\UserModel->findByEmail('admin@example.com')
 7 APPPATH/Controllers/Login.php(21): App\Libraries\Authentication->login('admin@example.com', 'secret', false)
 8 SYSTEMPATH/CodeIgniter.php(927): App\Controllers\Login->create()
 9 SYSTEMPATH/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
10 SYSTEMPATH/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
